import React, { useEffect, useState, useRef } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { getArtistDetails } from '../services/geminiService';
import { ArtistDetails } from '../types';
import Loader from '../components/Loader';
import { Disc, ArrowLeft, Edit, Save, X, Trash2, Image as ImageIcon, Facebook, Instagram, Youtube, PenTool, Music, Mic2, Star, User, Upload } from 'lucide-react';
import { useAuth } from '../utils/auth';
import { saveCustomArtist, deleteCustomArtist, getAllCustomSongs, parseArtistIdentifier } from '../utils/dataManager';
import { useLanguage } from '../contexts/LanguageContext';

interface DisplaySong {
    id: string;
    title: string;
    title_nepali?: string;
    mainArtist: string;
    language?: string;
    roles: string[]; // e.g., ['Composer', 'Lyricist']
    note?: string;
}

// Consistent default image for "Unknown" artists
const DEFAULT_UNKNOWN_IMAGE = "https://ui-avatars.com/api/?name=Unknown&background=e2e8f0&color=64748b&size=512";

const ArtistPage: React.FC = () => {
  const { name } = useParams<{ name: string }>();
  const [artist, setArtist] = useState<ArtistDetails | null>(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();
  const [displaySongs, setDisplaySongs] = useState<DisplaySong[]>([]);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const { language: appLanguage } = useLanguage();
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Admin / Edit State
  const { isAuth } = useAuth();
  const [isEditing, setIsEditing] = useState(false);
  const [editForm, setEditForm] = useState<ArtistDetails>({
      name: '',
      bio: '',
      topSongs: [],
      imageUrl: '',
      facebookUrl: '',
      instagramUrl: '',
      youtubeUrl: '',
      isFacebookVisible: true,
      isInstagramVisible: true,
      isArtistYoutubeVisible: true
  });
  const [topSongsString, setTopSongsString] = useState('');

  useEffect(() => {
    const fetchArtistAndSongs = async () => {
      if (name) {
        setLoading(true);
        const decodedIdentifier = decodeURIComponent(name);
        const { name: decodedName, id: artistId } = parseArtistIdentifier(decodedIdentifier);
        const lowerName = decodedName.toLowerCase().trim();
        
        if (lowerName === 'unknown') {
            setArtist(null);
            setLoading(false);
            return;
        }

        const dbProfile = await getArtistDetails(decodedIdentifier);
        const allSongs = await getAllCustomSongs();

        const matchedSongs: DisplaySong[] = allSongs.reduce((acc: DisplaySong[], s: any) => {
            const roles: string[] = [];
            
            // Helper to check if an identifier matches our current artist
            const isMatch = (identifier: string) => {
                const { name: n, id: i } = parseArtistIdentifier(identifier);
                if (artistId && i) {
                    return artistId === i;
                }
                return n.toLowerCase().trim() === lowerName;
            };

            // Correctly parse main artists to check if this artist is credited individually
            const mainArtists = (s.artists && s.artists.length > 0) 
                ? s.artists 
                : s.artist.split(',').map((a: string) => a.trim());

            if (mainArtists.some(isMatch)) roles.push('Main Artist');
            
            const compList = (s.composers || []).concat(s.composer ? [s.composer] : []);
            if (compList.some(isMatch)) roles.push('Composer');

            const lyrList = (s.lyricists || []).concat(s.lyricist ? [s.lyricist] : []);
            if (lyrList.some(isMatch)) roles.push('Lyricist');

            const singList = (s.singers || []).concat(s.singer ? [s.singer] : []);
            if (singList.some(isMatch)) roles.push('Vocals');

            if (roles.length > 0) {
                const existing = acc.find(item => item.id === s.id);
                if (!existing) {
                    acc.push({
                        id: s.id,
                        title: s.title,
                        title_nepali: s.title_nepali,
                        mainArtist: s.artist,
                        language: s.language,
                        roles: [...new Set(roles)],
                        note: s.note
                    });
                }
            }
            return acc;
        }, []);

        matchedSongs.sort((a, b) => {
            const aIsMain = a.roles.includes('Main Artist');
            const bIsMain = b.roles.includes('Main Artist');
            if (aIsMain && !bIsMain) return -1;
            if (!aIsMain && bIsMain) return 1;
            return a.title.localeCompare(b.title);
        });

        setDisplaySongs(matchedSongs);

        if (dbProfile) {
            setArtist(dbProfile);
            setIsAutoGenerated(false);
            setTopSongsString(dbProfile.topSongs.join(', '));
            setEditForm({ 
                ...dbProfile, 
                imageUrl: dbProfile.imageUrl || '',
                facebookUrl: dbProfile.facebookUrl || '',
                instagramUrl: dbProfile.instagramUrl || '',
                youtubeUrl: dbProfile.youtubeUrl || '',
                isFacebookVisible: dbProfile.isFacebookVisible !== false,
                isInstagramVisible: dbProfile.isInstagramVisible !== false,
                isArtistYoutubeVisible: dbProfile.isArtistYoutubeVisible !== false
            });
        } else if (matchedSongs.length > 0) {
            const virtualProfile: ArtistDetails = {
                name: decodedName,
                bio: `Profile automatically generated based on credits. ${decodedName} is credited as a ${matchedSongs[0]?.roles.filter(r => r !== 'Main Artist')[0] || 'Contributor'} on SansarPlus.`,
                topSongs: matchedSongs.slice(0, 5).map(s => s.title),
                imageUrl: '',
            };
            setArtist(virtualProfile);
            setIsAutoGenerated(true);
            setEditForm({ ...virtualProfile, 
                facebookUrl: '', instagramUrl: '', youtubeUrl: '', 
                isFacebookVisible: true, isInstagramVisible: true, isArtistYoutubeVisible: true 
            });
        } else {
            setArtist(null);
        }

        setLoading(false);
      }
    };
    fetchArtistAndSongs();
  }, [name]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
          setEditForm(prev => ({ ...prev, imageUrl: event.target?.result as string }));
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSaveEdit = () => {
      if (!artist) return;
      
      const updatedArtist = {
          ...editForm,
          topSongs: topSongsString.split(',').map(s => s.trim()).filter(s => s)
      };

      if (editForm.name !== artist.name) {
          if (window.confirm(`Renaming artist from "${artist.name}" to "${editForm.name}". This will create a new profile. Continue?`)) {
             saveCustomArtist(editForm.name, updatedArtist);
             if (!isAutoGenerated) {
                 deleteCustomArtist(artist.name);
             }
             navigate(`/artist/${encodeURIComponent(editForm.name)}`, { replace: true });
          }
      } else {
          saveCustomArtist(artist.name, updatedArtist);
          setArtist(updatedArtist);
          setIsAutoGenerated(false);
          setIsEditing(false);
      }
  };

  const handleDeleteArtist = () => {
      if (!artist) return;
      if (isAutoGenerated) {
          alert("This is an auto-generated profile based on song credits. It cannot be deleted directly. To remove it, remove the credits from the songs.");
          return;
      }
      if (window.confirm('Delete this artist profile? This will revert to AI generation or remove if custom.')) {
          deleteCustomArtist(artist.name);
          navigate('/');
      }
  };

  const getSongColorClass = (lang?: string) => {
      if (lang === 'hindi') return 'text-red-600';
      if (lang === 'english') return 'text-blue-600';
      return 'text-slate-800';
  };

  const renderRoleBadge = (role: string) => {
      switch(role) {
          case 'Composer': return <span key={role} className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-indigo-100 text-indigo-700 mr-1"><Music className="w-3 h-3 mr-1"/> Composer</span>;
          case 'Lyricist': return <span key={role} className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 mr-1"><PenTool className="w-3 h-3 mr-1"/> Lyrics</span>;
          case 'Vocals': return <span key={role} className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-pink-100 text-pink-700 mr-1"><Mic2 className="w-3 h-3 mr-1"/> Vocals</span>;
          default: return <span key={role} className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-600 mr-1">{role}</span>;
      }
  };

  if (loading) return <Loader fullScreen text="Loading profile..." />;
  if (!artist) return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50">
        <div className="text-center p-8">
            <h2 className="text-2xl font-bold text-slate-400 mb-2">Artist Not Found</h2>
            <p className="text-slate-500 mb-6">We couldn't find a profile or any songs credited to "{name}".</p>
            <Link to="/" className="text-primary font-bold hover:underline">Return Home</Link>
        </div>
    </div>
  );
  
  const displayImage = artist.imageUrl || null;

  return (
    <div className="min-h-screen bg-slate-50">
       <div className="bg-white border-b border-slate-200 shadow-sm">
            <div className="max-w-7xl mx-auto px-4 py-8">
                <Link to="/browse/artists/A" className="inline-flex items-center text-slate-500 hover:text-primary mb-6 transition-colors">
                    <ArrowLeft className="w-4 h-4 mr-2" /> Back to Browse
                </Link>
                
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
                    <div className="flex items-center gap-6">
                         {displayImage ? (
                             <div className="w-24 h-24 md:w-32 md:h-32 rounded-full overflow-hidden border-4 border-slate-100 shadow-md flex-shrink-0">
                                 <img src={displayImage} alt={artist.name} className="w-full h-full object-cover" />
                             </div>
                         ) : (
                             <div className="w-24 h-24 md:w-32 md:h-32 rounded-full bg-slate-100 flex items-center justify-center text-slate-300 shadow-inner flex-shrink-0">
                                 <ImageIcon className="w-10 h-10" />
                             </div>
                         )}

                         <div>
                             {isEditing ? (
                                 <input 
                                    type="text" 
                                    className="text-2xl md:text-3xl font-extrabold text-slate-900 border-b-2 border-primary focus:outline-none bg-transparent w-full"
                                    value={editForm.name}
                                    onChange={(e) => setEditForm({...editForm, name: e.target.value})}
                                 />
                             ) : (
                                 <div className="flex flex-col gap-2">
                                     <div className="flex items-center gap-2">
                                        <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight">{artist.name}</h1>
                                        {isAutoGenerated && <span className="px-2 py-1 bg-slate-100 text-slate-500 text-[10px] font-bold uppercase rounded tracking-wider border border-slate-200">Auto-Generated</span>}
                                     </div>
                                     <div className="flex flex-wrap gap-4 mt-1">
                                         {artist.facebookUrl && artist.isFacebookVisible !== false && (
                                             <a 
                                                href={artist.facebookUrl} 
                                                target="_blank" 
                                                rel="noopener noreferrer"
                                                className="flex items-center text-blue-600 hover:text-blue-700 font-bold transition-colors w-fit bg-blue-50 px-3 py-1 rounded-full text-sm"
                                             >
                                                 <Facebook className="w-4 h-4 mr-2" /> Facebook
                                             </a>
                                         )}
                                         {artist.instagramUrl && artist.isInstagramVisible !== false && (
                                             <a 
                                                href={artist.instagramUrl} 
                                                target="_blank" 
                                                rel="noopener noreferrer"
                                                className="flex items-center text-pink-600 hover:text-pink-700 font-bold transition-colors w-fit bg-pink-50 px-3 py-1 rounded-full text-sm"
                                             >
                                                 <Instagram className="w-4 h-4 mr-2" /> Instagram
                                             </a>
                                         )}
                                         {artist.youtubeUrl && artist.isArtistYoutubeVisible !== false && (
                                             <a 
                                                href={artist.youtubeUrl} 
                                                target="_blank" 
                                                rel="noopener noreferrer"
                                                className="flex items-center text-red-600 hover:text-red-700 font-bold transition-colors w-fit bg-red-50 px-3 py-1 rounded-full text-sm"
                                             >
                                                 <Youtube className="w-4 h-4 mr-2" /> YouTube
                                             </a>
                                         )}
                                     </div>
                                 </div>
                             )}
                         </div>
                    </div>
                    
                    {isAuth && (
                        <div className="flex gap-2 self-start md:self-center">
                            {isEditing ? (
                                    <button onClick={handleSaveEdit} className="p-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors flex items-center">
                                        <Save className="w-5 h-5 mr-2" /> Save
                                    </button>
                            ) : (
                                    <button onClick={() => setIsEditing(true)} className="p-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors flex items-center">
                                        <Edit className="w-5 h-5 mr-2" /> Edit
                                    </button>
                            )}
                            {isEditing && (
                                    <button onClick={() => setIsEditing(false)} className="p-2 bg-slate-500 text-white rounded-lg hover:bg-slate-600 transition-colors">
                                        <X className="w-5 h-5" />
                                    </button>
                            )}
                            {!isEditing && !isAutoGenerated && (
                                    <button onClick={handleDeleteArtist} className="p-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors flex items-center">
                                        <Trash2 className="w-5 h-5 mr-2" /> Delete
                                    </button>
                            )}
                        </div>
                    )}
                </div>
            </div>
       </div>

       <div className="max-w-7xl mx-auto px-4 py-12 grid grid-cols-1 lg:grid-cols-3 gap-12">
            <div className="lg:col-span-1 space-y-8">
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                    <h3 className="text-xl font-bold text-slate-900 mb-4">About</h3>
                    {isEditing ? (
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-bold text-slate-500 mb-1 uppercase">Profile Image</label>
                                <div className="flex flex-col gap-2">
                                    <div className="flex gap-2">
                                        <input 
                                            type="text" 
                                            className="flex-1 border p-2 rounded text-sm outline-none"
                                            value={editForm.imageUrl || ''}
                                            onChange={e => setEditForm({...editForm, imageUrl: e.target.value})}
                                            placeholder="https://..."
                                        />
                                        <button type="button" onClick={() => fileInputRef.current?.click()} className="p-2 bg-slate-100 rounded-lg hover:bg-slate-200" title="Upload Image"><Upload className="w-4 h-4"/></button>
                                        <input type="file" autoFocus ref={fileInputRef} className="hidden" accept="image/*" onChange={handleFileUpload} />
                                    </div>
                                    {editForm.imageUrl && (
                                        <div className="flex justify-center mt-2">
                                            <div className="w-20 h-20 rounded-full border-2 border-primary/20 overflow-hidden">
                                                <img src={editForm.imageUrl} className="w-full h-full object-cover" />
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                            
                            <div className="border-t border-b py-4 my-2 space-y-4">
                                <label className="block text-sm font-bold text-slate-500 mb-2 uppercase tracking-wide">Social Links</label>
                                <div className="space-y-3">
                                    <div className="flex items-center gap-2">
                                        <Facebook className="w-4 h-4 text-blue-500"/>
                                        <input className="flex-1 border p-2 rounded text-sm" value={editForm.facebookUrl || ''} onChange={e => setEditForm({...editForm, facebookUrl: e.target.value})} placeholder="Facebook URL" />
                                        <input type="checkbox" className="rounded" checked={editForm.isFacebookVisible} onChange={e => setEditForm({...editForm, isFacebookVisible: e.target.checked})} title="Visible?" />
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <Instagram className="w-4 h-4 text-pink-500"/>
                                        <input className="flex-1 border p-2 rounded text-sm" value={editForm.instagramUrl || ''} onChange={e => setEditForm({...editForm, instagramUrl: e.target.value})} placeholder="Instagram URL" />
                                        <input type="checkbox" className="rounded" checked={editForm.isInstagramVisible} onChange={e => setEditForm({...editForm, isInstagramVisible: e.target.checked})} title="Visible?" />
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <Youtube className="w-4 h-4 text-red-500"/>
                                        <input className="flex-1 border p-2 rounded text-sm" value={editForm.youtubeUrl || ''} onChange={e => setEditForm({...editForm, youtubeUrl: e.target.value})} placeholder="YouTube URL" />
                                        <input type="checkbox" className="rounded" checked={editForm.isArtistYoutubeVisible} onChange={e => setEditForm({...editForm, isArtistYoutubeVisible: e.target.checked})} title="Visible?" />
                                    </div>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-slate-500 mb-1 uppercase">Biography</label>
                                <textarea className="w-full h-80 border p-2 rounded text-sm outline-none focus:ring-1 focus:ring-primary/20 whitespace-pre-wrap" value={editForm.bio} onChange={e => setEditForm({...editForm, bio: e.target.value})} placeholder="Write biography in paragraphs..." />
                            </div>
                        </div>
                    ) : (
                        <div className="text-slate-600 leading-loose text-sm md:text-base mb-4 whitespace-pre-wrap">
                            {artist.bio || "No biography available."}
                        </div>
                    )}
                </div>
            </div>

            <div className="lg:col-span-2">
                <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center">
                    <Disc className="mr-3 text-primary" /> 
                    {isAutoGenerated ? 'Credited Songs' : 'Popular Tracks'}
                </h2>
                
                {isEditing && (
                    <div className="mb-4">
                        <label className="block text-sm font-bold text-slate-500 mb-1">Edit Songs (Legacy list, comma separated)</label>
                        <input type="text" className="w-full border p-3 rounded" value={topSongsString} onChange={e => setTopSongsString(e.target.value)} />
                    </div>
                )}

                <div className="space-y-3">
                    {displaySongs.length > 0 ? (
                        displaySongs.map((song, idx) => {
                            const displayTitle = (appLanguage === 'nepali' && song.title_nepali) ? song.title_nepali : song.title;
                            return (
                            <Link 
                                key={`${song.id}-${idx}`}
                                to={`/l/${song.id}`} // Updated to short URL
                                className="flex items-center justify-between p-4 rounded-xl bg-white hover:bg-slate-50 border border-slate-200 hover:border-primary/50 group transition-all shadow-sm hover:shadow-md"
                            >
                                <div className="flex items-center space-x-4">
                                    <span className="text-slate-400 font-mono w-6 text-center text-lg">{idx + 1}</span>
                                    <div>
                                        <div className="flex items-center flex-wrap gap-2 mb-0.5">
                                            <span className={`font-semibold transition-colors text-lg block ${getSongColorClass(song.language)}`}>
                                                {displayTitle}
                                                {song.note && <span className="ml-1.5 text-xs text-slate-400 font-medium italic">({song.note})</span>}
                                            </span>
                                            {song.roles.filter(r => r !== 'Main Artist').map(role => renderRoleBadge(role))}
                                        </div>
                                        {song.mainArtist.toLowerCase() !== artist.name.toLowerCase() && song.mainArtist.toLowerCase() !== 'unknown' && (
                                            <span className="text-xs text-slate-400">by <span className="font-bold">{song.mainArtist}</span></span>
                                        )}
                                    </div>
                                </div>
                                <span className="text-xs text-slate-500 px-3 py-1 border border-slate-200 rounded-full group-hover:border-primary/50 group-hover:text-primary transition-colors bg-slate-50">
                                    View Lyrics
                                </span>
                            </Link>
                        )})
                    ) : (
                        <p className="text-slate-500 italic">No songs found for this artist.</p>
                    )}
                </div>
            </div>
       </div>
    </div>
  );
};

export default ArtistPage;